# Site settings
title: LittleCheeseCake
email: yulu8798@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am migrating from a blog service provider to github, still trying out with Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yulu.github.io" # the base hostname & protocol for your site
twitter_username: little_cake_yl
github_username:  yulu

# Build settings
markdown: kramdown

# Time zone
timezone: Asia/Singapore
