# Site settings
title: LittleCheeseCake
email: yulu8798@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a software engineer, a blogger and a mother. This is a personal blog about my life and tech.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://littlecheesecake.me" # the base hostname & protocol for your site
twitter_username: little_cake_yl
github_username:  yulu

# Build settings
markdown: kramdown

# Time zone
timezone: Asia/Singapore

# Collections
collections:
  books:
    output: true

plugins:
  - jekyll-toc
  - jekyll-sitemap

